name: Bedwars
version: '${project.version}'
main: com.jason.main.bedwars
commands:
  join:
    description: a
  addGen:
  addShop:
  addShopDiamond:
  addSpawnColor:
  addSpawnTotal:
  addDiamondGen:
  addEmeraldGen:
  start:
  addArea:
  end:
  scan:
  npc:
  jerry:
  leave:
  l:
